Public class Conditional_Statement {
    Public 	Conditional_Statement()	{																																																																																																																																																																																																																																			
       integer i= 85;
        If(i<=85){
            System.debug('the given number is even number');
        }
        
    }
 }