public class My_Class3 {
    public string janasena ='Pawan Kalyan';
    public string actor = 'Chiranjeevi';
    public integer age =57;
    public decimal winpercentage =79.2;

    public My_Class3(){
       andhrapradeshpolitics(); 
    }

    public void andhrapradeshpolitics(){
        janasena ='pawan fans';
        age= 60;
        winpercentage = 89.52;
        System.debug('janasena' +janasena);
        System.debug('age'   +age);
        System.debug('winpercentage'  +winpercentage);
        
    }
}