public class StaticExample {
    Public static string stdname ='Srinu';
    Public static integer age = 22;
    Public static Decimal  fee = 50000;
    Public static string mobilenum ='9678546543';
    Public static string clgname;
    Public static boolean isactive;
    
    Public static void staticMethod(){
        clgname ='Gkce';
        isactive = False;
        System.debug('stdname'+stdname);
        System.debug('age'+age);
        System.debug('clgname'+clgname);
    }
   

}